/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.ContactInformation;
import Model.Person;
import javax.swing.JOptionPane; 

/**
 *
 * @author emi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Person person;
    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreateJPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldCurrentStreetName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldNuid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        fieldOfficePhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldOfficeEmail = new javax.swing.JTextField();
        fieldPersonalPhone = new javax.swing.JTextField();
        fieldPersonalEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldCurrentApt = new javax.swing.JTextField();
        fieldCurrentCityState = new javax.swing.JTextField();
        fieldCurrentZipCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fieldPermanentApt = new javax.swing.JTextField();
        fieldPermanentCityState = new javax.swing.JTextField();
        fieldPermanentZipCode = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fieldPermanentStreetName = new javax.swing.JTextField();
        ViewJPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewCurrentAddress = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        viewPermanentAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateJPanel.setBackground(new java.awt.Color(255, 255, 204));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Street Name");

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        jLabel3.setText("NUID");

        fieldNuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNuidActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name");

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        jLabel5.setText("College Name");

        jLabel6.setText("Office Phone");

        jLabel7.setText("Current Address");

        jLabel8.setText("Office Email");

        jLabel9.setText("Personal Phone");

        jLabel10.setText("Personal Email");

        jLabel11.setText("Apt No");

        jLabel12.setText("City/State");

        jLabel13.setText("Zip Code");

        jLabel14.setText("Permanent Address");

        jLabel15.setText("Apt No");

        jLabel16.setText("City/State");

        jLabel17.setText("Zip Code");

        jLabel18.setText("Street Name");

        javax.swing.GroupLayout CreateJPanelLayout = new javax.swing.GroupLayout(CreateJPanel);
        CreateJPanel.setLayout(CreateJPanelLayout);
        CreateJPanelLayout.setHorizontalGroup(
            CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(fieldNuid)
                    .addComponent(fieldOfficeEmail)
                    .addComponent(fieldOfficePhone)
                    .addComponent(fieldCollegeName)
                    .addComponent(fieldLastName)
                    .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(fieldCurrentStreetName)
                    .addComponent(fieldPersonalEmail)
                    .addComponent(fieldCurrentApt)
                    .addComponent(fieldCurrentCityState)
                    .addComponent(fieldCurrentZipCode))
                .addGap(55, 55, 55))
            .addGroup(CreateJPanelLayout.createSequentialGroup()
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldPermanentCityState, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPermanentApt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPermanentStreetName)
                            .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(saveButton)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        CreateJPanelLayout.setVerticalGroup(
            CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(fieldCurrentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(fieldCurrentApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(fieldCurrentCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fieldCurrentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(CreateJPanelLayout.createSequentialGroup()
                        .addComponent(fieldPermanentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPermanentApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPermanentCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(22, 22, 22))
        );

        jSplitPane1.setLeftComponent(CreateJPanel);

        ViewJPanel.setBackground(new java.awt.Color(204, 204, 255));

        name.setText("First Name");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel19.setText("Husky Card Details");

        jLabel20.setText("Office Phone");

        jLabel21.setText("Current Address");

        jLabel22.setText("Office Email");

        jLabel23.setText("Personal Phone");

        jLabel24.setText("Personal Email");

        jLabel25.setText("NUID");

        jLabel26.setText("Last Name");

        jLabel28.setText("College Name");

        jLabel27.setText("Permanent Address");

        javax.swing.GroupLayout ViewJPanelLayout = new javax.swing.GroupLayout(ViewJPanel);
        ViewJPanel.setLayout(ViewJPanelLayout);
        ViewJPanelLayout.setHorizontalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewJPanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel19))
                    .addGroup(ViewJPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28))
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))
                        .addGap(58, 58, 58)
                        .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCurrentAddress)
                            .addComponent(viewPersonalEmail)
                            .addComponent(viewPersonalPhone)
                            .addComponent(viewOfficeEmail)
                            .addComponent(viewNuid)
                            .addComponent(viewFirstName)
                            .addComponent(viewLastName)
                            .addComponent(viewCollegeName)
                            .addComponent(viewOfficePhone)
                            .addComponent(viewPermanentAddress))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        ViewJPanelLayout.setVerticalGroup(
            ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(33, 33, 33)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(viewNuid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(viewFirstName))
                .addGap(15, 15, 15)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(viewLastName))
                .addGap(12, 12, 12)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(viewCollegeName))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(viewOfficePhone))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(viewOfficeEmail))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(viewPersonalPhone))
                .addGap(17, 17, 17)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(viewPersonalEmail))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(viewCurrentAddress))
                .addGap(18, 18, 18)
                .addGroup(ViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(viewPermanentAddress))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(ViewJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        //collect input data
        String nuid = fieldNuid.getText();
        String firstName = fieldFirstName.getText(); 
        String lastName = fieldLastName.getText();
        String collegeName = fieldCollegeName.getText();
        String officePhone = fieldOfficePhone.getText();
        String officeEmail = fieldOfficeEmail.getText();
        String personalPhone = fieldPersonalPhone.getText();
        String personalEmail = fieldPersonalEmail.getText();
        String currentApt = fieldCurrentApt.getText();
        String currentStreet = fieldCurrentStreetName.getText();
        String currentCityState = fieldCurrentCityState.getText();
        String currentZipCode = fieldCurrentZipCode.getText();
        String perApt = fieldPermanentApt.getText();
        String perStreet = fieldPermanentStreetName.getText();
        String perCityState = fieldPermanentCityState.getText();
        String perZipCode = fieldPermanentZipCode.getText();
//        String officeContactInfo = "Phone: " + fieldOfficePhone.getText() + "|" + "Email: " + fieldOfficeEmail.getText();
//        String personalContactInfo = "Phone: " + fieldPersonalPhone.getText() + "|" + "Email: " + fieldPersonalEmail.getText();
//        String currentAddress = fieldCurrentApt.getText() + ", " + fieldCurrentStreetName.getText()
//                + ", " + fieldCurrentCityState.getText() + ", " + fieldCurrentZipCode.getText();
//        String permanentAddress = fieldPermanentApt.getText() + ", " + fieldPermanentStreetName.getText()
//                + ", " + fieldPermanentCityState.getText() + ", " + fieldPermanentZipCode.getText();
        
        //pass data to the person object
        this.person.setNuid(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        //pass contact info
        this.person.getOfficeContactInfo().setPhone(officePhone);
        this.person.getOfficeContactInfo().setEmail(officeEmail);
        this.person.getPersonalContactInfo().setPhone(personalPhone);
        this.person.getPersonalContactInfo().setEmail(personalEmail);
        //pass address
        this.person.getCurrentAddress().setAptNo(currentApt);
        this.person.getCurrentAddress().setStreetName(currentStreet);
        this.person.getCurrentAddress().setCityState(currentCityState);
        this.person.getCurrentAddress().setZipCode(currentZipCode);
        this.person.getPermanentAddress().setAptNo(perApt);
        this.person.getPermanentAddress().setStreetName(perStreet);
        this.person.getPermanentAddress().setCityState(perCityState);
        this.person.getPermanentAddress().setZipCode(perZipCode);
        
        JOptionPane.showMessageDialog(null,"SAVED DUCCESSFULLY!");
        
        display();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldNuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNuidActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void display(){
        viewNuid.setText(this.person.getNuid());
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewCollegeName.setText(this.person.getCollegeName());
        viewOfficePhone.setText(this.person.getOfficeContactInfo().getPhone());
        viewOfficeEmail.setText(this.person.getOfficeContactInfo().getEmail());
        viewPersonalPhone.setText(this.person.getPersonalContactInfo().getPhone());
        viewPersonalEmail.setText(this.person.getPersonalContactInfo().getEmail());
        viewCurrentAddress.setText(this.person.getCurrentAddress().getAptNo() + ", " + this.person.getCurrentAddress().getStreetName()
        + ", " + this.person.getCurrentAddress().getCityState() + ", " + this.person.getCurrentAddress().getZipCode());
        viewPermanentAddress.setText(this.person.getPermanentAddress().getAptNo() + ", " + this.person.getPermanentAddress().getStreetName()
        + ", " + this.person.getPermanentAddress().getCityState() + ", " + this.person.getPermanentAddress().getZipCode());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldCurrentApt;
    private javax.swing.JTextField fieldCurrentCityState;
    private javax.swing.JTextField fieldCurrentStreetName;
    private javax.swing.JTextField fieldCurrentZipCode;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermanentApt;
    private javax.swing.JTextField fieldPermanentCityState;
    private javax.swing.JTextField fieldPermanentStreetName;
    private javax.swing.JTextField fieldPermanentZipCode;
    private javax.swing.JTextField fieldPersonalEmail;
    private javax.swing.JTextField fieldPersonalPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel name;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewCurrentAddress;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermanentAddress;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    // End of variables declaration//GEN-END:variables
}
